#!/bin/sh

set -eu

if [ -z "${SKIP_STATIC_CHECK:-}" ]; then
    # run static code checks like flake8 and mypy
    PYEXEFILES="$(git grep -lI '^#!.*python') $(git ls-files "*.py")"
    flake8 $PYEXEFILES
fi

./test-bots
