#!/bin/sh

set -eu

if [ -z "${SKIP_STATIC_CHECK:-}" ]; then
    # run static code checks like flake8 and mypy
    PYEXEFILES="$(echo $(git grep -lI '^#!.*python') $(git ls-files "*.py") | xargs -n 1 | sort -u)"
    flake8 $PYEXEFILES

    mypy --no-error-summary --ignore-missing-imports --scripts-are-modules $PYEXEFILES
fi

./test-bots
